"""Added EbayItem class

Revision ID: 183493a890f2
Revises: f3d977e81412
Create Date: 2021-08-01 22:14:40.566167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183493a890f2'
down_revision = 'f3d977e81412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_image', sa.String(length=64000), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_item_average_image'), 'ebay_item', ['average_image'], unique=False)
    op.create_index(op.f('ix_ebay_item_last_updated'), 'ebay_item', ['last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ebay_item_last_updated'), table_name='ebay_item')
    op.drop_index(op.f('ix_ebay_item_average_image'), table_name='ebay_item')
    op.drop_table('ebay_item')
    # ### end Alembic commands ###
