"""changes for exercising

Revision ID: 714eb572c843
Revises: 0cacb12ff836
Create Date: 2021-07-27 15:04:50.583072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714eb572c843'
down_revision = '0cacb12ff836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_streak_streak_begin'), 'streak', ['streak_begin'], unique=False)
    op.create_index(op.f('ix_streak_streak_end'), 'streak', ['streak_end'], unique=False)
    op.create_index(op.f('ix_streak_total_count'), 'streak', ['total_count'], unique=False)
    op.add_column('user', sa.Column('last_exercised', sa.Date(), nullable=True))
    op.create_index(op.f('ix_user_last_exercised'), 'user', ['last_exercised'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_exercised'), table_name='user')
    op.drop_column('user', 'last_exercised')
    op.drop_index(op.f('ix_streak_total_count'), table_name='streak')
    op.drop_index(op.f('ix_streak_streak_end'), table_name='streak')
    op.drop_index(op.f('ix_streak_streak_begin'), table_name='streak')
    # ### end Alembic commands ###
