"""removed ExerciseDay

Revision ID: 7713d8fa8220
Revises: 714eb572c843
Create Date: 2021-07-27 17:07:18.898178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7713d8fa8220'
down_revision = '714eb572c843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercise_day_timestamp', table_name='exercise_day')
    op.drop_table('exercise_day')
    op.add_column('user', sa.Column('daily_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'daily_count')
    op.create_table('exercise_day',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('daily_count', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('streak_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['streak_id'], ['streak.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercise_day_timestamp', 'exercise_day', ['timestamp'], unique=False)
    # ### end Alembic commands ###
