"""added old_user field

Revision ID: b3a3d26760dc
Revises: 7713d8fa8220
Create Date: 2021-07-28 13:36:15.078454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a3d26760dc'
down_revision = '7713d8fa8220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streak', sa.Column('old_user', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_streak_old_user'), 'streak', ['old_user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streak_old_user'), table_name='streak')
    op.drop_column('streak', 'old_user')
    # ### end Alembic commands ###
