"""changed field name EbayItem

Revision ID: c427e4a898b0
Revises: 99c873873b7f
Create Date: 2021-08-01 23:31:30.829515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c427e4a898b0'
down_revision = '99c873873b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebay_item', sa.Column('png_image', sa.String(length=64000), nullable=True))
    op.drop_index('ix_ebay_item_average_image', table_name='ebay_item')
    op.create_index(op.f('ix_ebay_item_png_image'), 'ebay_item', ['png_image'], unique=False)
    op.drop_column('ebay_item', 'average_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebay_item', sa.Column('average_image', sa.VARCHAR(length=64000), nullable=True))
    op.drop_index(op.f('ix_ebay_item_png_image'), table_name='ebay_item')
    op.create_index('ix_ebay_item_average_image', 'ebay_item', ['average_image'], unique=False)
    op.drop_column('ebay_item', 'png_image')
    # ### end Alembic commands ###
