"""Users random exercise seeds

Revision ID: f3d977e81412
Revises: 06c88ebc30cd
Create Date: 2021-08-01 01:00:42.651990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d977e81412'
down_revision = '06c88ebc30cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daily_seed', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'daily_seed')
    # ### end Alembic commands ###
